language: node_js
node_js:
- '4'
- stable

notifications:
  emails: false

before_install:
- npm install eslint

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: aeH7uruaCVdorxzhRlSP/3YpBTKy1sDhmNZO1NO94QtQTepLuNPIzaxdqy/V3tc0hk36Osz4zaqH0uCDCrcsh+eq2eCjdfTUsBSQF/Xn8FHbe2w8U/d4fwsktZkuzDlIVNF2hZYUfoNzUBveFyzHBifjB2o21sUN92qVGsLlsHbyGZ/wXuR67/Bhr49iKdoXHm65mj1k2SSBoE0tR3oB27jxsx+vVSpG/7TbNG9k1AKFeivl5UCTqwDpWwIMicigsqjUpvxoflhd8XQOQ6/Sz/crlCtpEBlkcKGcQdD9kP5el/pDKCHLWUmugeyHPHnJrqx/8Z/fHSF+U0Ftk64SbNGQC5v4EsnfwAQ7S+BKlZlj6Ztf45tOEdYB1QrvNGm2BiCOlrObwAQDwTJti1Cf8wZcSKSuF2AjLptWKLYKBzHmYfNL8/8b6P+wGc3fA9kfB1zDsrjHAAmbUh/mPoQDCELZSCHTXoe3PyJdrar9Ufll0magp2jQqZS3OXv1XGgNWp5MWFrGeHhB3elkY0vohTohLpiPCaAVP5Y6oRsdyPQrvMjkPRgHa+yxa8zu+yx90qQ1+bmLS7IaC6Kgr7xpWNgdcwEOTxQvE3ycOX9xJ89ZWchISJP56AmQHgYLuCiBVbai4PB2b2a42NoWlapvm+O3qNl06I0D3xUtKzLX+Cw=
  on:
    tags: true
    repo: trailsjs/eslint-config-trails
